server:
  port: 9090

#数据库
spring:
  application:
    name: gxswaggergithub2.0 #微服务唯一标识，总是放在第一行
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.3.32.85:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&failOverReadOnly=false&secondsBeforeRetryMaster=0&queriesBeforeRetryMaster=0
    username: root
    password: roottest

    #增加druid的配置
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j


  jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true

  #打印真实的sql
#  jpa:
#    show-sql: true
#    database: mysql
#    generate-ddl: true
#    hibernate:
#      name:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  aop:
    proxy-target-class: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  ## Redis 配置
  redis:
     database: 4  # Redis数据库索引（默认为0）
     host: 10.3.5.38 # Redis服务器地址
     port: 6379 # Redis服务器连接端口
     password:   # Redis服务器连接密码（默认为空）

  #控制台输出的json更加美观
  jackson:
    serialization:
      indent_output: true

  #配置ActiveMQ的消息代理的地址
  activemq:
    broker-url: tcp://10.3.5.45:61616
    in-memory: true
    user: admin
    password: admin
    packages:
     trust-all: true  #白名单
    pool:
      expiry-timeout: 0 #连接超时超时毫秒。
      idle-timeout: 30000 #连接空闲超时（毫秒）。
      max-connections: 1 #汇集连接的最大数目。





#dubbo配置
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    protocol: zookeeper
    address: 10.3.5.36:2181
  annotation:
    package: com.jztey.${spring.application.name}
  provider:
    timeout: 15000
  consumer:
    check: false
    timeout: 15000


logging:
  file: ${spring.application.name}.log

#访问Druid的帐号和密码
druid:
  loginUsername: druid
  loginPassword: 123456
  allow: 127.0.0.1 #白名单
  deny: 192.168.0.99 #黑名单
  resetEnable: false #是否重置数据
  exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"  #忽略路径